/** Hebrew labels + intake priority for employee card fields. */
export const CANDIDATE_FIELD_META: { key: string; label: string; priority: number }[] = [
  { key: "desiredRole", label: "תפקיד מבוקש", priority: 1 },
  { key: "field", label: "תחום", priority: 2 },
  { key: "subField", label: "תת-תחום", priority: 3 },
  { key: "location", label: "מיקום עיקרי", priority: 4 },
  { key: "preferredCities", label: "ערים מועדפות", priority: 5 },
  { key: "remotePreference", label: "העדפת ריחוק/היברידי", priority: 6 },
  { key: "relocationWillingness", label: "נכונות למעבר", priority: 7 },
  { key: "experienceYears", label: "שנות ניסיון", priority: 8 },
  { key: "experienceLevel", label: "רמת ניסיון", priority: 9 },
  { key: "workHistory", label: "היסטוריית תעסוקה", priority: 10 },
  { key: "skills", label: "כישורים מקצועיים", priority: 11 },
  { key: "softSkills", label: "כישורים רכים", priority: 12 },
  { key: "languages", label: "שפות", priority: 13 },
  { key: "hebrewLevel", label: "רמת עברית", priority: 14 },
  { key: "englishLevel", label: "רמת אנגלית", priority: 15 },
  { key: "education", label: "השכלה", priority: 16 },
  { key: "educationHistory", label: "היסטוריית השכלה", priority: 17 },
  { key: "certifications", label: "הסמכות", priority: 18 },
  { key: "licenses", label: "רישיונות", priority: 19 },
  { key: "computerSkills", label: "מיומנויות מחשב", priority: 20 },
  { key: "salaryExpectation", label: "ציפיית שכר", priority: 21 },
  { key: "salaryMin", label: "שכר מינימום", priority: 22 },
  { key: "salaryMax", label: "שכר מקסימום", priority: 23 },
  { key: "employmentType", label: "סוג העסקה", priority: 24 },
  { key: "hoursPerWeek", label: "שעות בשבוע", priority: 25 },
  { key: "shiftPreference", label: "העדפת משמרות", priority: 26 },
  { key: "nightShiftsOk", label: "משמרות לילה", priority: 27 },
  { key: "weekendsOk", label: "סופי שבוע", priority: 28 },
  { key: "transportation", label: "תחבורה", priority: 29 },
  { key: "hasVehicle", label: "רכב פרטי", priority: 30 },
  { key: "drivingLicense", label: "רישיון נהיגה", priority: 31 },
  { key: "personality", label: "אופי", priority: 32 },
  { key: "workStyle", label: "סגנון עבודה", priority: 33 },
  { key: "strengths", label: "חוזקות", priority: 34 },
  { key: "weaknesses", label: "נקודות לשיפור", priority: 35 },
  { key: "careerGoals", label: "יעדי קריירה", priority: 36 },
  { key: "motivation", label: "מוטיבציה", priority: 37 },
  { key: "dealBreakers", label: "קווים אדומים", priority: 38 },
  { key: "noticePeriod", label: "תקופת הודעה מוקדמת", priority: 39 },
  { key: "startDate", label: "תאריך התחלה אפשרי", priority: 40 },
  { key: "availability", label: "זמינות כללית", priority: 41 },
  { key: "interviewAvailability", label: "זמינות לראיון", priority: 42 },
  { key: "customerFacingOk", label: "עבודה מול קהל", priority: 43 },
  { key: "physicalRequirementsOk", label: "דרישות פיזיות", priority: 44 },
  { key: "managementExperience", label: "ניסיון ניהולי", priority: 45 },
  { key: "teamSizeManaged", label: "גודל צוות שנוהל", priority: 46 },
  { key: "industryExperience", label: "ניסיון ענפי", priority: 47 },
  { key: "portfolioUrl", label: "תיק עבודות / קישור", priority: 48 },
  { key: "linkedinUrl", label: "LinkedIn", priority: 49 },
  { key: "referencesAvailable", label: "ממליצים", priority: 50 },
  { key: "narrative", label: "טקסט חופשי / סיפור", priority: 51 },
  { key: "flexibility", label: "גמישות התאמה (1–10)", priority: 52 },
  { key: "summary", label: "סיכום", priority: 53 },
];

export const JOB_FIELD_META: { key: string; label: string; priority: number }[] = [
  { key: "title", label: "כותרת משרה", priority: 1 },
  { key: "field", label: "תחום", priority: 2 },
  { key: "subField", label: "תת-תחום", priority: 3 },
  { key: "location", label: "מיקום", priority: 4 },
  { key: "workModel", label: "מודל עבודה", priority: 5 },
  { key: "scope", label: "היקף משרה", priority: 6 },
  { key: "employmentType", label: "סוג העסקה", priority: 7 },
  { key: "hoursPerWeek", label: "שעות בשבוע", priority: 8 },
  { key: "shiftPattern", label: "מבנה משמרות", priority: 9 },
  { key: "nightShiftsRequired", label: "דורש משמרות לילה", priority: 10 },
  { key: "weekendsRequired", label: "דורש סופי שבוע", priority: 11 },
  { key: "salaryRange", label: "טווח שכר", priority: 12 },
  { key: "salaryMin", label: "שכר מינימום", priority: 13 },
  { key: "salaryMax", label: "שכר מקסימום", priority: 14 },
  { key: "benefits", label: "הטבות", priority: 15 },
  { key: "mustHaves", label: "דרישות חובה", priority: 16 },
  { key: "niceToHaves", label: "יתרון", priority: 17 },
  { key: "requiredLanguages", label: "שפות נדרשות", priority: 18 },
  { key: "requiredLicenses", label: "רישיונות נדרשים", priority: 19 },
  { key: "requiredEducation", label: "השכלה נדרשת", priority: 20 },
  { key: "minExperienceYears", label: "מינימום שנות ניסיון", priority: 21 },
  { key: "seniorityLevel", label: "רמת בכירות", priority: 22 },
  { key: "toolsRequired", label: "כלים/מערכות", priority: 23 },
  { key: "personalityFit", label: "אופי מתאים", priority: 24 },
  { key: "teamCulture", label: "תרבות צוות", priority: 25 },
  { key: "managementStyle", label: "סגנון ניהול", priority: 26 },
  { key: "teamSize", label: "גודל צוות", priority: 27 },
  { key: "reportsTo", label: "מדווח ל", priority: 28 },
  { key: "customerFacing", label: "עבודה מול לקוחות", priority: 29 },
  { key: "physicalDemands", label: "דרישות פיזיות", priority: 30 },
  { key: "dressCode", label: "קוד לבוש", priority: 31 },
  { key: "transportNeeded", label: "דרישת תחבורה/רכב", priority: 32 },
  { key: "startDate", label: "תאריך התחלה רצוי", priority: 33 },
  { key: "urgency", label: "דחיפות גיוס", priority: 34 },
  { key: "interviewSlots", label: "חלונות לראיון", priority: 35 },
  { key: "interviewProcess", label: "תהליך ראיונות", priority: 36 },
  { key: "probationPeriod", label: "תקופת ניסיון", priority: 37 },
  { key: "growthPath", label: "מסלול התפתחות", priority: 38 },
  { key: "companyDescription", label: "תיאור החברה/עסק", priority: 39 },
  { key: "companySize", label: "גודל ארגון", priority: 40 },
  { key: "industry", label: "ענף", priority: 41 },
  { key: "dealBreakers", label: "קווים אדומים למועמד", priority: 42 },
  { key: "successMetrics", label: "מדדי הצלחה בתפקיד", priority: 43 },
  { key: "onboardingNotes", label: "הערות קליטה", priority: 44 },
  { key: "contactName", label: "איש קשר לגיוס", priority: 45 },
  { key: "contactPhone", label: "טלפון ליצירת קשר", priority: 46 },
  { key: "narrative", label: "טקסט חופשי / סיפור על המשרה", priority: 47 },
  { key: "flexibility", label: "גמישות בדרישות (1–10)", priority: 48 },
  { key: "summary", label: "סיכום משרה", priority: 49 },
];
